ec-nopCommerce-xl/src/Presentation/Nop.Web/Administration/Controllers/ScheduleTaskController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Nop.Admin.Models.Tasks;
using Nop.Core.Domain.Tasks;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Tasks;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Controllers
{
    public partial class ScheduleTaskController : BaseAdminController
	{
		#region Fields

        private readonly IScheduleTaskService _scheduleTaskService;
        private readonly IPermissionService _permissionService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly ILocalizationService _localizationService;

		#endregion

		#region Constructors

        public ScheduleTaskController(IScheduleTaskService scheduleTaskService, 
            IPermissionService permissionService,
            IDateTimeHelper dateTimeHelper, ILocalizationService localizationService)
		{
            this._scheduleTaskService = scheduleTaskService;
            this._permissionService = permissionService;
            this._dateTimeHelper = dateTimeHelper;
            this._localizationService = localizationService;
		}

		#endregion 

        #region Utility

        [NonAction]
        protected virtual ScheduleTaskModel PrepareScheduleTaskModel(ScheduleTask task)
        {
            var model = new ScheduleTaskModel
                            {
                                Id = task.Id,
                                Name = task.Name,
                                Seconds = task.Seconds,
                                Enabled = task.Enabled,
                                StopOnError = task.StopOnError,
                                LastStartUtc = task.LastStartUtc.HasValue ? _dateTimeHelper.ConvertToUserTime(task.LastStartUtc.Value, DateTimeKind.Utc).ToString("G") : "",
                                LastEndUtc = task.LastEndUtc.HasValue ? _dateTimeHelper.ConvertToUserTime(task.LastEndUtc.Value, DateTimeKind.Utc).ToString("G") : "",
                                LastSuccessUtc = task.LastSuccessUtc.HasValue ? _dateTimeHelper.ConvertToUserTime(task.LastSuccessUtc.Value, DateTimeKind.Utc).ToString("G") : "",
                            };
            return model;
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageScheduleTasks))
                return AccessDeniedView();

            return View();
		}

		[HttpPost]
        public ActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageScheduleTasks))
                return AccessDeniedView();

            var models = _scheduleTaskService.GetAllTasks(true)
                .Select(PrepareScheduleTaskModel)
                .ToList();
            var gridModel = new DataSourceResult
            {
                Data = models,
                Total = models.Count
            };

            return Json(gridModel);
		}

        [HttpPost]
        public ActionResult TaskUpdate(ScheduleTaskModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageScheduleTasks))
                return AccessDeniedView();

            if (!ModelState.IsValid)
            {
                return Json(new DataSourceResult { Errors = ModelState.SerializeErrors() });
            }

            var scheduleTask = _scheduleTaskService.GetTaskById(model.Id);
            if (scheduleTask == null)
                return Content("Schedule task cannot be loaded");

            scheduleTask.Name = model.Name;
            scheduleTask.Seconds = model.Seconds;
            scheduleTask.Enabled = model.Enabled;
            scheduleTask.StopOnError = model.StopOnError;
            _scheduleTaskService.UpdateTask(scheduleTask);

            return new NullJsonResult();
        }

        public ActionResult RunNow(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageScheduleTasks))
                return AccessDeniedView();

            try
            {
                var scheduleTask = _scheduleTaskService.GetTaskById(id);
                if (scheduleTask == null)
                    throw new Exception("Schedule task cannot be loaded");

                var task = new Task(scheduleTask);
                //ensure that the task is enabled
                task.Enabled = true;
                //do not dispose. otherwise, we can get exception that DbContext is disposed
                task.Execute(true, false);
                SuccessNotification(_localizationService.GetResource("Admin.System.ScheduleTasks.RunNow.Done"));
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
            }

            return RedirectToAction("List");
        }
        #endregion
    }
}

ec-nopCommerce-xl/src/Presentation/Nop.Web/Administration/Views/ScheduleTask/List.cshtml
@{
    //page title
    ViewBag.Title = T("Admin.System.ScheduleTasks").Text;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
        @T("Admin.System.ScheduleTasks")
    </div>
</div>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#schedule-tasks-grid").on("click", ".run-now", function (e) {
                showThrobber('@Html.Raw(HttpUtility.JavaScriptStringEncode(T("Admin.System.ScheduleTasks.RunNow.Progress").Text))');
            });
        });
    </script>    
<table class="adminContent">
    <tr>
        <td>
            <strong>@T("Admin.System.ScheduleTasks.RestartApplication")</strong>
        </td>
    </tr>
    <tr>
        <td>
            <div id="schedule-tasks-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#schedule-tasks-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("List", "ScheduleTask"))",
                                    type: "POST",
                                    dataType: "json"
                                },
                                update: {
                                    url:"@Html.Raw(Url.Action("TaskUpdate", "ScheduleTask"))",
                                    type: "POST",
                                    dataType: "json"
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors",
                                model: {
                                    id: "Id",
                                    fields: {
                                        Name: { editable: true, type: "string" },
                                        Seconds: { editable: true, type: "number" },
                                        Enabled: { editable: true, type: "boolean" },
                                        StopOnError: { editable: true, type: "boolean" },
                                        LastStartUtc: { editable: false, type: "date" },
                                        LastEndUtc: { editable: false, type: "date" },
                                        LastSuccessUtc: { editable: false, type: "date" },
                                        Id: { editable: false, type: "number" }
                                    }
                                }
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "Name",
                            title: "@T("Admin.System.ScheduleTasks.Name")",
                            width: 300
                        }, {
                            field: "Seconds",
                            title: "@T("Admin.System.ScheduleTasks.Seconds")",
                            width: 50
                        }, {
                            field: "Enabled",
                            title: "@T("Admin.System.ScheduleTasks.Enabled")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=Enabled#.gif" />'
                        }, {
                            field: "StopOnError",
                            title: "@T("Admin.System.ScheduleTasks.StopOnError")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=StopOnError#.gif" />'
                        }, {
                            field: "LastStartUtc",
                            title: "@T("Admin.System.ScheduleTasks.LastStart")",
                            width: 200,
                            type: "date",
                            format: "{0:G}"
                        }, {
                            field: "LastEndUtc",
                            title: "@T("Admin.System.ScheduleTasks.LastEnd")",
                            width: 200,
                            type: "date",
                            format: "{0:G}"
                        }, {
                            field: "LastSuccessUtc",
                            title: "@T("Admin.System.ScheduleTasks.LastSuccess")",
                            width: 200,
                            type: "date",
                            format: "{0:G}"
                        }, {
                            field: "Id",
                            title: "@T("Admin.System.ScheduleTasks.RunNow")",
                            width: 100,
                            template: '<a href="@Url.Content("~/Admin/ScheduleTask/RunNow/")#=Id#" class="k-button run-now">@T("Admin.System.ScheduleTasks.RunNow")</a>'
                        }, {
                            command: { name: "edit", text: "@T("Admin.Common.Edit")" },
                            title: "@T("Admin.Common.Edit")",
                            width: 100
                        }]
                    });
                });
            </script>
        </td>
    </tr>
</table>